swagger: "2.0"
info:
  description: "Here you can find API provided for an Alarms Repository server.\n You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/)."
  version: "1.0.0"
  title: "Alarms Repository"
host: "localhost:8080"
basePath: "/alarms"
tags:
- name: "alarms"
  description: "API for alarms"
schemes:
- "http"
paths:
  /:
    get:
      tags:
      - "alarms"
      summary: "Returns all alarms in the Repository"
      operationId: "xyz1"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Alarm"
        "400":
          description: "Invalid status value"
    post:
      tags:
      - "alarms"
      summary: "Updates the Repository with a new alarm"
      description: ""
      operationId: "xyz3"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"
  /{alarmId}:
    get:
      tags:
      - "alarms"
      summary: "Returns an alarm by a given Notification Identifier"
      description: "Returns a single alarm"
      operationId: "xyz2"
      produces:
      - "application/json"
      parameters:
      - name: "alarmId"
        in: "path"
        description: "Alarm Notification Identifier of pet to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Alarm"
        "400":
          description: "Invalid Notification Identifier supplied"
        "404":
          description: "Alarm not found"
    delete:
      tags:
      - "alarms"
      summary: "Deletes an alarm from the Repository"
      description: ""
      operationId: "xyz4"
      produces:
      - "application/json"
      parameters:
      - name: "alarmId"
        in: "path"
        description: "Alarm id to delete"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid Notification Identifier supplied"
        "404":
          description: "Alarm not found"
definitions:
  PerceivedSeverity:
    type: "string"
    enum:
    - INDETERMINATE
    - CRITICAL
    - MAJOR
    - MINOR
    - WARNING
    - CLEARED
    
  Alarm:
    type: "object"
    properties:
      NotificationIdentifier:
        type: "string"
      Severity:
        $ref: "#/definitions/PerceivedSeverity"
      EventTime:
        type: "object"
        description: "java.util.Date"
      ProbableCause:
        type: "string"
      AdditionalText:
        type: "string"
        